# Generated by Django 3.2 on 2021-05-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20210502_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='goottext',
            field=models.TextField(blank=True, default='a', null=True),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='sns_image',
            field=models.ImageField(upload_to=' '),
        ),
    ]
