# Generated by Django 3.2 on 2021-05-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_auto_20210503_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmodel',
            old_name='goottext',
            new_name='goodtext',
        ),
    ]
